# Generated by Django 2.2.5 on 2019-10-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('fy_0', models.IntegerField()),
                ('fy_1', models.IntegerField()),
                ('fy_2', models.IntegerField()),
                ('fy_3', models.IntegerField()),
                ('fy_combined', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuccessFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('fy_0', models.IntegerField()),
                ('fy_1', models.IntegerField()),
                ('fy_2', models.IntegerField()),
                ('fy_3', models.IntegerField()),
                ('fy_combined', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
